server:
  port: 8083

spring:
  application:
    name: ms-pedidos360-notifications
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

---
# Perfil local: desarrollo directo en la maquina (sin Docker)
spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: localhost
    port: 5672
  devtools:
    restart:
      enabled: true

---
# Perfil docker: contenedor dentro de docker compose
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq1
    port: 5672