name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create .env file from GitHub Secrets
      working-directory: ./infra
      run: |
        echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "AZURE_AD_TENANT_ID=${{ secrets.AZURE_AD_TENANT_ID }}" >> .env
        echo "AZURE_AD_CLIENT_ID=${{ secrets.AZURE_AD_CLIENT_ID }}" >> .env
        echo "API_CLIENT_ID=${{ secrets.API_CLIENT_ID }}" >> .env
        echo "JWT_ISSUER_URI=${{ secrets.JWT_ISSUER_URI }}" >> .env
        echo "VITE_BFF_URL=${{ secrets.VITE_BFF_URL }}" >> .env

    - name: Build Docker images
      working-directory: ./infra
      run: docker compose build
